### ISSUE TITLE
Jupyter notebooks

### ISSUE THREAD

**Issue by frere-jacques** [francma/everforest-jetbrains#6]
The jupyter notebooks look messed up with this theme. Background is bright.
Are there any plans to support notebooks?

**Comment by francma** [comment]
I have no plans for it at the moment as I mostly focus on languages that I directly use.

Pull requests are welcome

**Comment by frere-jacques** [comment]
I can understand that. No clue whether this is an easy task or not. The code in the notebooks is Python so it should work. It's maybe more like the other issue I created regarding other terminal windows.

**Comment by frere-jacques** [comment]
So I found out what one needs to do to make it nicer via IDE settings. But I don't know how that needs to be entered into theme.

Settings -> Editor -> Color Scheme -> Notebooks -> Code cell background : untick background.
It's nice to change input excecution count and current cell stripe too.

**Comment by francma** [comment]
You need to export the updated theme to .icls (which is just a plain XML file) via "Settings > Editor > Color Schemes > gear icon next to theme name > export > icls", find the updated values (they are usually prefixed with language name) and then create file `src/includes/jupyter.xml` (with color codes instead of hex colors). You can find more on how to do this in projects README.

**Comment by frere-jacques** [comment]
I created a pull request for the terminal issue. I have only the community version at home. If everything works with this pull request I will create one for jupyter support with theme export from work.

**Comment by francma** [comment]
Closed in https://github.com/francma/everforest-jetbrains/pull/8
